# Generated by Django 5.0.7 on 2024-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.TimeField(),
        ),
    ]
