# Generated by Django 5.0.7 on 2024-07-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_post_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
