# Generated by Django 5.0.7 on 2024-07-27 00:41

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_post_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
