# Generated by Django 5.0.7 on 2024-07-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
