# Generated by Django 5.0.7 on 2024-07-27 03:18

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_video_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
