# Generated by Django 5.1rc1 on 2024-07-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
