# Generated by Django 5.1rc1 on 2024-07-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
