# Generated by Django 5.1rc1 on 2024-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_delete_video_remove_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imdb',
        ),
        migrations.AddField(
            model_name='post',
            name='zip_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
