# Generated by Django 5.1rc1 on 2024-07-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_post_imdb_post_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='zip_file',
        ),
    ]
