# Generated by Django 5.1rc1 on 2024-08-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_post_header_post_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='progress',
        ),
    ]
