# Generated by Django 5.1rc1 on 2024-08-04 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_post_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('grade', models.FloatField()),
                ('file', models.FileField(null=True, upload_to='cheatsheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cheat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.cheat'),
        ),
    ]
