# Generated by Django 5.1rc1 on 2024-08-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_movie_remove_post_cheat_delete_cheat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
