# Generated by Django 5.1rc1 on 2024-08-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_post_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie',
        ),
    ]
