# Generated by Django 5.1rc1 on 2024-08-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_remove_post_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
