# Generated by Django 5.1rc1 on 2024-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_remove_post_movie_movie_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.TimeField(),
        ),
    ]
